name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        java:
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
    runs-on: ubuntu-latest
    name: Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: ./gradlew assemble
      - run: ./gradlew check
